version: '3.7'
services: 
    php:
        build: 
            context: ./docker/php
            args: 
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        user: "${UID}:${GID}"
        volumes: 
            - .:/var/www:delegated
        links: 
            - db
        depends_on: 
            - db

    nginx:
        image: nginx:1.19.0
        user: "${UID}:${GID}"
        ports: 
            - 8000:80
        volumes: 
            - .:/var/www:delegated
            - ./www.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
        links: 
            - php
        environment: 
            TIMEZONE: Europe/Paris

    db:
        # This image exposes the standard MySQL port (3306)
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db
        # phpmyadmin port defined to 3002
        ports:
            - "3002:80"